# Generated by Django 3.2.8 on 2022-01-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.TextField()),
                ('title', models.TextField()),
                ('price', models.IntegerField()),
                ('popularity', models.IntegerField()),
            ],
        ),
    ]
