# Generated by Django 3.2.8 on 2022-01-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='subid',
            field=models.IntegerField(default=0),
        ),
    ]
